# Generated by Django 4.1.3 on 2023-06-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_organisation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='file',
            field=models.FileField(default=0, upload_to='org_com/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
