# Generated by Django 4.1.3 on 2023-10-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_orgcomittee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcomittee',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
