# Generated by Django 4.1.3 on 2023-10-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_orgcomittee_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgcomittee',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
