# Generated by Django 4.1.3 on 2023-10-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_orgcomittee_org_alter_orgcomittee_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=7)),
                ('semester', models.SmallIntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
