# Generated by Django 4.1.3 on 2023-10-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_inactive',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
    ]
