# Generated by Django 4.1.3 on 2023-10-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_date_inactive_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_inactive',
            field=models.DateField(null=True),
        ),
    ]
