# Generated by Django 4.1.3 on 2023-10-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_date_joined'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Lecturer',
        ),
    ]
