# Generated by Django 4.1.3 on 2023-10-30 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_lecturer_students_student_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrol_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grad_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
