# Generated by Django 4.1.3 on 2023-10-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_student_enrol_year_alter_student_grad_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_chi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
