# Generated by Django 4.1.3 on 2023-11-13 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_lecturer_user_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrol_sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrol_sem', to='users.semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='grad_sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grad_sem', to='users.semester'),
        ),
    ]
