# Generated by Django 4.1.3 on 2023-11-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_student_enrol_sem_student_grad_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
