# Generated by Django 4.1.3 on 2023-11-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_semester_end_alter_semester_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cd_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pd_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rm_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='viva_date',
            field=models.DateTimeField(null=True),
        ),
    ]
