# Generated by Django 4.1.3 on 2024-01-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrol_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grad_year',
        ),
    ]
