# Generated by Django 4.1.3 on 2024-01-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_student_enrol_year_remove_student_grad_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='file_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student'),
        ),
    ]
