# Generated by Django 4.1.3 on 2023-06-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('General', 'General'), ('Event', 'Event'), ('Others', 'Others')], max_length=10)),
                ('display_to', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('award', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('attendance', models.BooleanField(default=0, null=True)),
                ('registered', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50, unique=True)),
                ('e_name', models.CharField(max_length=50, unique=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Seminar'), (2, 'Conference'), (3, 'Proposal Defense'), (4, 'Candidatual Defense'), (5, 'Freshman Month / Week'), (6, 'The Night of Chinese Studies Department'), (7, 'Creative Writing'), (8, 'Others')])),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('internal', models.BooleanField()),
                ('speaker', models.CharField(max_length=50)),
                ('attendance', models.BooleanField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OtherComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('award', models.CharField(max_length=50)),
            ],
        ),
    ]
