# Generated by Django 4.1.3 on 2023-06-12 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='othercomp',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AddField(
            model_name='event_participants',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.events'),
        ),
        migrations.AddField(
            model_name='event_participants',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AddField(
            model_name='comittee',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='events.events'),
        ),
        migrations.AddField(
            model_name='comittee',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.organisation'),
        ),
        migrations.AddField(
            model_name='comittee',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.student'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
