# Generated by Django 4.1.3 on 2023-06-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='file',
            field=models.FileField(upload_to='event_com/'),
        ),
    ]
