# Generated by Django 4.1.3 on 2023-06-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='c_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='e_name',
            field=models.CharField(max_length=50),
        ),
    ]
