# Generated by Django 4.1.3 on 2023-06-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_events_c_name_alter_events_e_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='file',
        ),
    ]
