# Generated by Django 4.1.3 on 2023-06-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_events_file_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
