# Generated by Django 4.1.3 on 2023-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_events_file_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.BooleanField(),
        ),
    ]
