# Generated by Django 4.1.3 on 2023-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_events_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='display_to',
            field=models.CharField(choices=[('Undergrad', 'Undergrad'), ('Postgrad', 'Postgrad'), ('All', 'All')], max_length=10),
        ),
    ]
