# Generated by Django 4.1.3 on 2023-09-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_announcement_title_alter_announcement_display_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'General'), (2, 'Event'), (3, 'Others')]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='display_to',
            field=models.SmallIntegerField(choices=[(1, 'All'), (2, 'Undergrad'), (3, 'Postgrad')]),
        ),
    ]
