# Generated by Django 4.1.3 on 2023-09-21 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_events_file_remove_events_file_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_participants',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.events'),
        ),
    ]
