# Generated by Django 4.1.3 on 2023-09-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_orgcomittee'),
        ('events', '0016_alter_event_participants_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_form',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event_form',
            name='submit_by',
        ),
        migrations.RemoveField(
            model_name='event_participants',
            name='event_form',
        ),
        migrations.AddField(
            model_name='events',
            name='file',
            field=models.FileField(null=True, upload_to='event_com/'),
        ),
        migrations.AddField(
            model_name='events',
            name='file_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student'),
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Comittee',
        ),
        migrations.DeleteModel(
            name='Event_Form',
        ),
    ]
