# Generated by Django 4.1.3 on 2023-09-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_event_form_event_remove_event_form_submit_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='attendance',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='c_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='poster',
            field=models.FileField(null=True, upload_to='event_poster/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='speaker',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Seminar'), (2, 'Conference'), (3, 'Proposal Defense'), (4, 'Candidatual Defense'), (5, 'Freshman Month / Week'), (6, 'The Night of Chinese Studies Department'), (7, 'Creative Writing'), (8, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
