# Generated by Django 4.1.3 on 2023-09-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_events_attendance_alter_events_c_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_participants',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
