# Generated by Django 4.1.3 on 2023-10-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_events_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercomp',
            name='file',
            field=models.FileField(null=True, upload_to='event_other/'),
        ),
        migrations.AddField(
            model_name='othercomp',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
