# Generated by Django 4.1.3 on 2023-10-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_othercomp_file_othercomp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_participants',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='othercomp',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
