# Generated by Django 4.1.3 on 2023-10-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_participants_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_participants',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
