# Generated by Django 4.1.3 on 2023-10-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_events_attendance_ontime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='attendance_ontime',
            new_name='enable_attendance',
        ),
    ]
