# Generated by Django 4.1.3 on 2023-10-31 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_rename_attendance_ontime_events_enable_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_participants',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
    ]
