# Generated by Django 4.1.3 on 2023-06-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50, null=True)),
                ('comp', models.CharField(max_length=100, null=True)),
                ('award', models.CharField(max_length=50, null=True)),
                ('submission', models.FileField(upload_to='')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
