# Generated by Django 4.1.3 on 2023-06-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(default=0, upload_to='article'),
            preserve_default=False,
        ),
    ]
