# Generated by Django 4.1.3 on 2023-06-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_file', models.FileField(upload_to='event_com/')),
                ('org_file', models.FileField(upload_to='org_com/')),
                ('article_file', models.FileField(upload_to='article/')),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
    ]
