# Generated by Django 4.1.3 on 2023-06-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_uploads_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='article_file',
            field=models.FileField(default=None, upload_to='article/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='event_file',
            field=models.FileField(default=None, upload_to='event_com/'),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='org_file',
            field=models.FileField(default=None, upload_to='org_com/'),
        ),
    ]
