# Generated by Django 4.1.3 on 2023-06-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_uploads_article_file_alter_uploads_event_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploads',
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(default=0, upload_to='article/'),
            preserve_default=False,
        ),
    ]
