# Generated by Django 4.1.3 on 2023-06-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='student',
            new_name='file_by',
        ),
        migrations.RemoveField(
            model_name='article',
            name='submission',
        ),
    ]
