# Generated by Django 4.1.3 on 2023-10-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_rename_student_article_file_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
        migrations.AddField(
            model_name='article',
            name='art_front',
            field=models.FileField(null=True, upload_to='article/'),
        ),
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.FileField(null=True, upload_to='article/'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal_front',
            field=models.FileField(null=True, upload_to='article/'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal_last',
            field=models.FileField(null=True, upload_to='article/'),
        ),
        migrations.AddField(
            model_name='article',
            name='proof',
            field=models.FileField(null=True, upload_to='article/'),
        ),
    ]
