# Generated by Django 4.1.3 on 2023-10-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='art_front',
        ),
        migrations.RemoveField(
            model_name='article',
            name='journal_front',
        ),
        migrations.RemoveField(
            model_name='article',
            name='journal_last',
        ),
    ]
