# Generated by Django 4.1.3 on 2023-10-31 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_lecturer_user_alter_student_user'),
        ('articles', '0020_rename_file_by_article_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
