# Generated by Django 4.1.3 on 2023-11-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_article_apa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(null=True),
        ),
    ]
